### ISSUE TITLE
Can't load resources (connect to meteor) in step 11

### ISSUE THREAD

**Issue by pkitatta** [Urigo/Ionic2CLI-Meteor-WhatsApp#114]
Even after adding meteor-client.config.json the chat doesn't connect to meteor and hence can't get passed the login page.

deviceready has not fired after 5 seconds. cordova.js:1223
Channel not fired: onDOMContentLoaded cordova.js:1216
Angular is running in the development mode. Call enableProdMode() to enable the production mode. vendor.js:3554
Angular is running in the development mode. Call enableProdMode() to enable the production mode. vendor.js:3554
Failed to load resource http://localhost:3000/sockjs/info?cb=fw4trhioui
Ionic Native: deviceready did not fire within 5000ms. This can happen when plugins are in an inconsistent state. Try removing plugins from plugins/ and reinstalling them. vendor.js:208998
Ionic Native: deviceready event fired after 51682 ms vendor.js:208993
Failed to load resource file:///android_asset/www/build/Observable.js.map
Failed to load resource file:///android_asset/www/build/index.js.map
Failed to load resource http://localhost:3000/sockjs/info?cb=z_nwg9qt3d
Failed to load resource http://localhost:3000/sockjs/info?cb=gh8fqmogs6
Failed to load resource http://localhost:3000/sockjs/info?cb=wygfk7cjwc
Failed to load resource http://localhost:3000/sockjs/info?cb=uwo8m60e0w
Failed to load resource http://localhost:3000/sockjs/info?cb=o6da85n6lz
Failed to load resource http://localhost:3000/sockjs/info?cb=7y6_iergk9
Failed to load resource http://localhost:3000/sockjs/info?cb=l725lqot0t
Failed to load resource http://localhost:3000/sockjs/info?cb=paa8qepq91
Failed to load resource http://localhost:3000/sockjs/info?cb=xr4bf9yxiu
Failed to load resource http://localhost:3000/sockjs/info?cb=el_o7qb8jw

Anyone have an idea how to solve this. The app works well in the browser - just not on android.

**Comment by airstep** [comment]
Maybe you need to use ip address of your notebook or server, but not localhost.

**Comment by sigalor** [comment]
Right, apparently the problem is that the app still thinks it is running on your local computer. I'd suggest you to do the following:

1. Terminate all running Ionic/Meteor processes, of course.
2. Figure out the local IP address of your computer (run `ipconfig` on Windows CMD or `ifconfig` on Linux). It will probably look something like `192.168.1.103`. In the following, replace this address with yours everywhere.
3. In `config.xml` set the appropriate line to `<content original-src="index.html" src="http://192.168.1.103:8100" />`.
4. Add the following line to `config.xml`: `<allow-navigation href="http://192.168.1.103:8100" />`.
5. Make sure that your `meteor-client.config.json` really contains the value `http://192.168.1.103:3000` for `runtime.DDP_DEFAULT_CONNECTION_URL`.
6. In your `package.json` file, make sure the `scripts.api` string is set to `"cd api && export ROOT_URL=http://192.168.1.103:3000 && meteor run --settings private/settings.json"` (omit the `--settings` parameter if you did not read about it in the tutorial yet). Also set the `scripts.api:reset` to `"cd api && export ROOT_URL=http://192.168.1.103:3000 && meteor reset"`.

Actually, I just started learning Ionic/Meteor/... myself, so I am not 100% sure if all of these steps are really necessary. But, at least for me, the app now runs perfectly fine on my Android device.

By the way, in your next issue report, please include much more information about your development environment, e.g. the output of `ionic info`, the actual content of `meteor-client.config.json` and other important configuration files like `package.json`, `webpack.config.js` and `config.xml` and everything else that you think might help others understand your issue better. I am sure that this way, you are going to receive much more helpful answers! :)

**Comment by pkitatta** [comment]
Hi @sigalor, thanks for your response. I have tried your solution but now I get a new error that says 'page not available' and shows ' Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png data:text/html,chro…:12 in the console.
The app still works in the browser.
As regards the development environment everything is as par the tutorial step 11, I have only made changes as par your suggestions above. Although I have to mention I am using windows 7, I just realised of late the errors on windows are more than those of other systems.
The other value I changed is that of "loadUrlTimeoutValue" to a much bigger number. This was while troubleshooting the same issue. It only helped the browser app to start working properly. It almost seemed like the android app suffered from the same but increasing the number to an extravagant billion does help. I even reinstalled the plugins

Maybe just to share some of my files

config.xml:

<?xml version='1.0' encoding='utf-8'?>
<widget id="io.ionic.starter" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>MyApp</name>
    <description>An awesome Ionic/Cordova app.</description>
    <author email="hi@ionicframework" href="http://ionicframework.com/">Ionic Framework Team</author>
    <content original-src="index.html" src="http://192.168.8.100:8100" />
    <access origin="*" />
    <allow-navigation href="http://192.168.8.100:8100" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <preference name="webviewbounce" value="false" />
    <preference name="UIWebViewBounce" value="false" />
    <preference name="DisallowOverscroll" value="true" />
    <preference name="android-minSdkVersion" value="16" />
    <preference name="BackupWebStorage" value="none" />
    <preference name="SplashMaintainAspectRatio" value="true" />
    <preference name="FadeSplashScreenDuration" value="300" />
    <preference name="SplashShowOnlyFirstTime" value="false" />
    <preference name="SplashScreen" value="screen" />
    <preference name="SplashScreenDelay" value="3000" />
    <preference name="loadUrlTimeoutValue" value="700000000000" />
    <platform name="android">
        <allow-intent href="market:*" />
        <icon density="ldpi" src="resources/android/icon/drawable-ldpi-icon.png" />
        <icon density="mdpi" src="resources/android/icon/drawable-mdpi-icon.png" />
        <icon density="hdpi" src="resources/android/icon/drawable-hdpi-icon.png" />
        <icon density="xhdpi" src="resources/android/icon/drawable-xhdpi-icon.png" />
        <icon density="xxhdpi" src="resources/android/icon/drawable-xxhdpi-icon.png" />
        <icon density="xxxhdpi" src="resources/android/icon/drawable-xxxhdpi-icon.png" />
        <splash density="land-ldpi" src="resources/android/splash/drawable-land-ldpi-screen.png" />
        <splash density="land-mdpi" src="resources/android/splash/drawable-land-mdpi-screen.png" />
        <splash density="land-hdpi" src="resources/android/splash/drawable-land-hdpi-screen.png" />
        <splash density="land-xhdpi" src="resources/android/splash/drawable-land-xhdpi-screen.png" />
        <splash density="land-xxhdpi" src="resources/android/splash/drawable-land-xxhdpi-screen.png" />
        <splash density="land-xxxhdpi" src="resources/android/splash/drawable-land-xxxhdpi-screen.png" />
        <splash density="port-ldpi" src="resources/android/splash/drawable-port-ldpi-screen.png" />
        <splash density="port-mdpi" src="resources/android/splash/drawable-port-mdpi-screen.png" />
        <splash density="port-hdpi" src="resources/android/splash/drawable-port-hdpi-screen.png" />
        <splash density="port-xhdpi" src="resources/android/splash/drawable-port-xhdpi-screen.png" />
        <splash density="port-xxhdpi" src="resources/android/splash/drawable-port-xxhdpi-screen.png" />
        <splash density="port-xxxhdpi" src="resources/android/splash/drawable-port-xxxhdpi-screen.png" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
        <icon height="57" src="resources/ios/icon/icon.png" width="57" />
        <icon height="114" src="resources/ios/icon/icon@2x.png" width="114" />
        <icon height="40" src="resources/ios/icon/icon-40.png" width="40" />
        <icon height="80" src="resources/ios/icon/icon-40@2x.png" width="80" />
        <icon height="120" src="resources/ios/icon/icon-40@3x.png" width="120" />
        <icon height="50" src="resources/ios/icon/icon-50.png" width="50" />
        <icon height="100" src="resources/ios/icon/icon-50@2x.png" width="100" />
        <icon height="60" src="resources/ios/icon/icon-60.png" width="60" />
        <icon height="120" src="resources/ios/icon/icon-60@2x.png" width="120" />
        <icon height="180" src="resources/ios/icon/icon-60@3x.png" width="180" />
        <icon height="72" src="resources/ios/icon/icon-72.png" width="72" />
        <icon height="144" src="resources/ios/icon/icon-72@2x.png" width="144" />
        <icon height="76" src="resources/ios/icon/icon-76.png" width="76" />
        <icon height="152" src="resources/ios/icon/icon-76@2x.png" width="152" />
        <icon height="167" src="resources/ios/icon/icon-83.5@2x.png" width="167" />
        <icon height="29" src="resources/ios/icon/icon-small.png" width="29" />
        <icon height="58" src="resources/ios/icon/icon-small@2x.png" width="58" />
        <icon height="87" src="resources/ios/icon/icon-small@3x.png" width="87" />
        <splash height="1136" src="resources/ios/splash/Default-568h@2x~iphone.png" width="640" />
        <splash height="1334" src="resources/ios/splash/Default-667h.png" width="750" />
        <splash height="2208" src="resources/ios/splash/Default-736h.png" width="1242" />
        <splash height="1242" src="resources/ios/splash/Default-Landscape-736h.png" width="2208" />
        <splash height="1536" src="resources/ios/splash/Default-Landscape@2x~ipad.png" width="2048" />
        <splash height="2048" src="resources/ios/splash/Default-Landscape@~ipadpro.png" width="2732" />
        <splash height="768" src="resources/ios/splash/Default-Landscape~ipad.png" width="1024" />
        <splash height="2048" src="resources/ios/splash/Default-Portrait@2x~ipad.png" width="1536" />
        <splash height="2732" src="resources/ios/splash/Default-Portrait@~ipadpro.png" width="2048" />
        <splash height="1024" src="resources/ios/splash/Default-Portrait~ipad.png" width="768" />
        <splash height="960" src="resources/ios/splash/Default@2x~iphone.png" width="640" />
        <splash height="480" src="resources/ios/splash/Default~iphone.png" width="320" />
    </platform>
    <engine name="android" spec="^6.2.3" />
    <plugin name="cordova-plugin-console" spec="^1.0.7" />
    <plugin name="cordova-plugin-device" spec="^1.1.6" />
    <plugin name="cordova-plugin-splashscreen" spec="^4.0.3" />
    <plugin name="cordova-plugin-statusbar" spec="^2.2.3" />
    <plugin name="cordova-plugin-whitelist" spec="^1.3.2" />
    <plugin name="ionic-plugin-keyboard" spec="^2.2.1" />
</widget>


package.json:
{
    "name": "front3",
    "version": "0.0.1",
    "author": "Ionic Framework",
    "homepage": "http://ionicframework.com/",
    "private": true,
    "scripts": {
        "api": "cd api && export ROOT_URL=http://192.168.8.100:3000 && meteor reset",
        "clean": "ionic-app-scripts clean",
        "build": "ionic-app-scripts build",
        "lint": "ionic-app-scripts lint",
        "ionic:build": "ionic-app-scripts build",
        "ionic:serve": "ionic-app-scripts serve",
        "meteor-client:bundle": "meteor-client bundle -s api -c meteor-client.config.json"
    },
    "dependencies": {
        "@angular/common": "4.1.3",
        "@angular/compiler": "4.1.3",
        "@angular/compiler-cli": "4.1.3",
        "@angular/core": "4.1.3",
        "@angular/forms": "4.1.3",
        "@angular/http": "4.1.3",
        "@angular/platform-browser": "4.1.3",
        "@angular/platform-browser-dynamic": "4.1.3",
        "@ionic-native/core": "3.12.1",
        "@ionic-native/splash-screen": "3.12.1",
        "@ionic-native/status-bar": "3.12.1",
        "@ionic/storage": "2.0.1",
        "angular2-moment": "^1.4.0",
        "babel-runtime": "^6.20.0",
        "cordova-android": "^6.2.3",
        "cordova-plugin-console": "^1.0.7",
        "cordova-plugin-device": "^1.1.6",
        "cordova-plugin-splashscreen": "^4.0.3",
        "cordova-plugin-statusbar": "^2.2.3",
        "cordova-plugin-whitelist": "^1.3.2",
        "ionic-angular": "3.5.2",
        "ionic-plugin-keyboard": "^2.2.1",
        "ionicons": "3.0.0",
        "meteor-node-stubs": "^0.2.11",
        "meteor-rxjs": "^0.4.7",
        "moment": "^2.18.1",
        "rxjs": "5.4.0",
        "sw-toolbox": "3.6.0",
        "zone.js": "0.8.12"
    },
    "devDependencies": {
        "@ionic/app-scripts": "2.0.2",
        "@ionic/cli-plugin-cordova": "1.5.0",
        "@ionic/cli-plugin-ionic-angular": "1.4.0",
        "@types/meteor": "^1.4.2",
        "@types/meteor-accounts-phone": "0.0.5",
        "@types/meteor-publish-composite": "0.0.32",
        "@types/underscore": "^1.8.1",
        "ionic": "3.6.0",
        "meteor-typings": "^1.4.1",
        "tmp": "0.0.31",
        "typescript": "2.3.4",
        "typescript-extends": "^1.0.1"
    },
    "description": "front3: An Ionic project",
    "config": {
        "ionic_webpack": "./webpack.config.js"
    },
    "cordova": {
        "plugins": {
            "cordova-plugin-console": {},
            "cordova-plugin-device": {},
            "cordova-plugin-splashscreen": {},
            "cordova-plugin-statusbar": {},
            "cordova-plugin-whitelist": {},
            "ionic-plugin-keyboard": {}
        },
        "platforms": [
            "android"
        ]
    }
}

meteor-client.config.json:

{
  "runtime": {
    "DDP_DEFAULT_CONNECTION_URL": "http://192.168.8.100:3000",
    "ROOT_URL": "http://192.168.8.100:3000"
  },
  "import": [

  ]
}

webpack.config.js

var path = require('path');
var webpack = require('webpack');
var ionicWebpackFactory = require(process.env.IONIC_WEBPACK_FACTORY);

var ModuleConcatPlugin = require('webpack/lib/optimize/ModuleConcatenationPlugin');

var prodPlugins = [];
if (process.env.IONIC_ENV === 'prod') {
  prodPlugins.push(new ModuleConcatPlugin());
}webpack.config.js

module.exports = {
  entry: process.env.IONIC_APP_ENTRY_POINT,
  output: {
    path: '{{BUILD}}',
    publicPath: 'build/',
    filename: '[name].js',
    devtoolModuleFilenameTemplate: ionicWebpackFactory.getSourceMapperFunction(),
  },
  devtool: process.env.IONIC_SOURCE_MAP_TYPE,

  resolve: {
    extensions: ['.ts', '.js', '.json'],
    modules: [path.resolve('node_modules')],
    alias: {
      'api': path.resolve(__dirname, 'api/server')
    }
  },

  externals: [
    resolveExternals
  ],

  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.ts$/,
        loader: process.env.IONIC_WEBPACK_LOADER
      },
      {
        test: /\.js$/,
        loader: process.env.IONIC_WEBPACK_TRANSPILE_LOADER
      }
    ]
  },

  plugins: [
    ionicWebpackFactory.getIonicEnvironmentPlugin(),
    ionicWebpackFactory.getCommonChunksPlugin(),
    new webpack.ProvidePlugin({
      __extends: 'typescript-extends'
    })
  ].concat(prodPlugins),

  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    __dirname: true
  }
};

function resolveExternals(context, request, callback) {
  return resolveMeteor(request, callback) ||
    callback();
}

function resolveMeteor(request, callback) {
  var match = request.match(/^meteor\/(.+)$/);
  var pack = match && match[1];

  if (pack) {
    callback(null, 'Package["' + pack + '"]');
    return true;
  }
}

If you have any other ideas please tell.

**Comment by sigalor** [comment]
Well, I guess I have to admit that this begins to exceed my current knowledge... Especially because I haven't had this error myself before. I do know that `loadUrlTimeoutValue` really is necessary for Android to tolerate long loading delays.

Maybe another idea of mine could help you nevertheless: I also tried a Cordova build on my Android 5.0.1 device (what's your Android version, by the way?). A bit later in the tutorial, in step 13, choosing files from the phone's gallery is implemented. I saw that this worked perfectly fine in my desktop browser, but failed on Android with some "permission error" as well. It turned out that this had to do with the fact that I passed `--livereload` as command line parameter to `cordova` (I added a script to package.json for this task: `"ionic:android-device": "ionic cordova run android --livereload --device --address 192.168.1.103"`). Without it I didn't have the sweet live reload function but at least this detail of the app worked.

So, I hope others from this community can help you better. After all, another well-meant tip for you: [Wrap all of your posted code in three backticks](https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks) to make it easier for everyone to read it. :)

**Comment by pkitatta** [comment]
Are you using windows?

**Comment by sigalor** [comment]
No, Ubuntu 16.04.

**Comment by pkitatta** [comment]
That explains one of my points I made earlier on; windows is such a pain. For-example the app has been working well on the browser with only this current issue as my pressure point, but just yesterday I got `Cannot find module "meteor/meteor"` out of the blue!

**Comment by sigalor** [comment]
Well, I switched from Windows to Ubuntu as my main system around three years ago, although I still have another Windows 10 production machine I use for work occasionally. Anyway, of course Linux generally is more developer-friendly, I would rather "blame" Node.js and all of the other JavaScript frameworks (and after all, JavaScript is, or at least should be, platform independent). They are still very young and not as mature as C, C++ or Java (I have used these languages for many years in the past as well).
But, and that's the reason why I begun learning to use them at all: They are something new and, if you know enough workarounds for all bugs and issues they have, you can do big things with them rather easily.

Okay, I think all of my rambling won't help you much... Of course I don't know your current situation, but currently, I personally don't _have to_ use Ionic/... in any production environment. I am learning this entirely for fun. Maybe I am just in a very lucky situation, but maybe you are too. :)

Finally, I may also have a solution for your most recent problem: Just remove all lines like `import { Meteor } from 'meteor/meteor';`. I have had exactly the same error myself as well. Someone else made me write my solution down to this and some other errors [here](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/113#issuecomment-318623523).

**Comment by darkbasic** [comment]
Closing due to inactivity and cleanup after tons of new updates.
Feel free to open a new issue if you are still affected.
